package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1



/**
 * CartHasProducts generated by hbm2java
 */
public class CartHasProducts  implements java.io.Serializable {


     private Integer cpid;
     private Cart cart;
     private Products products;
     private Double price;
     private Integer qty;

    public CartHasProducts() {
    }

    public CartHasProducts(Cart cart, Products products, Double price, Integer qty) {
       this.cart = cart;
       this.products = products;
       this.price = price;
       this.qty = qty;
    }
   
    public Integer getCpid() {
        return this.cpid;
    }
    
    public void setCpid(Integer cpid) {
        this.cpid = cpid;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


