package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private User user;
     private Double tprice;
     private Integer tqty;
     private String st;
     private Set<CartHasProducts> cartHasProductses = new HashSet<CartHasProducts>(0);

    public Cart() {
    }

	
    public Cart(User user) {
        this.user = user;
    }
    public Cart(User user, Double tprice, Integer tqty, String st, Set<CartHasProducts> cartHasProductses) {
       this.user = user;
       this.tprice = tprice;
       this.tqty = tqty;
       this.st = st;
       this.cartHasProductses = cartHasProductses;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getTprice() {
        return this.tprice;
    }
    
    public void setTprice(Double tprice) {
        this.tprice = tprice;
    }
    public Integer getTqty() {
        return this.tqty;
    }
    
    public void setTqty(Integer tqty) {
        this.tqty = tqty;
    }
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }
    public Set<CartHasProducts> getCartHasProductses() {
        return this.cartHasProductses;
    }
    
    public void setCartHasProductses(Set<CartHasProducts> cartHasProductses) {
        this.cartHasProductses = cartHasProductses;
    }




}


