package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer idcomments;
     private Products products;
     private String comment;
     private String st;

    public Comments() {
    }

	
    public Comments(Products products) {
        this.products = products;
    }
    public Comments(Products products, String comment, String st) {
       this.products = products;
       this.comment = comment;
       this.st = st;
    }
   
    public Integer getIdcomments() {
        return this.idcomments;
    }
    
    public void setIdcomments(Integer idcomments) {
        this.idcomments = idcomments;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }




}


