package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idinvoice;
     private User user;
     private Double tprice;
     private Date idate;
     private Integer tqty;
     private String st;
     private Set<InvoiceHasProducts> invoiceHasProductses = new HashSet<InvoiceHasProducts>(0);

    public Invoice() {
    }

	
    public Invoice(User user) {
        this.user = user;
    }
    public Invoice(User user, Double tprice, Date idate, Integer tqty, String st, Set<InvoiceHasProducts> invoiceHasProductses) {
       this.user = user;
       this.tprice = tprice;
       this.idate = idate;
       this.tqty = tqty;
       this.st = st;
       this.invoiceHasProductses = invoiceHasProductses;
    }
   
    public Integer getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(Integer idinvoice) {
        this.idinvoice = idinvoice;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getTprice() {
        return this.tprice;
    }
    
    public void setTprice(Double tprice) {
        this.tprice = tprice;
    }
    public Date getIdate() {
        return this.idate;
    }
    
    public void setIdate(Date idate) {
        this.idate = idate;
    }
    public Integer getTqty() {
        return this.tqty;
    }
    
    public void setTqty(Integer tqty) {
        this.tqty = tqty;
    }
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }
    public Set<InvoiceHasProducts> getInvoiceHasProductses() {
        return this.invoiceHasProductses;
    }
    
    public void setInvoiceHasProductses(Set<InvoiceHasProducts> invoiceHasProductses) {
        this.invoiceHasProductses = invoiceHasProductses;
    }




}


