package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1



/**
 * InvoiceHasProducts generated by hbm2java
 */
public class InvoiceHasProducts  implements java.io.Serializable {


     private Integer ipid;
     private Invoice invoice;
     private Products products;
     private Double price;
     private Integer qty;

    public InvoiceHasProducts() {
    }

    public InvoiceHasProducts(Invoice invoice, Products products, Double price, Integer qty) {
       this.invoice = invoice;
       this.products = products;
       this.price = price;
       this.qty = qty;
    }
   
    public Integer getIpid() {
        return this.ipid;
    }
    
    public void setIpid(Integer ipid) {
        this.ipid = ipid;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


