package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Loginlog generated by hbm2java
 */
public class Loginlog  implements java.io.Serializable {


     private Integer idloginlog;
     private User user;
     private Date logintime;
     private Date logouttime;
     private Date logindate;
     private Date logoutdate;
     private String st;
     private Set<Activity> activities = new HashSet<Activity>(0);
     private Set<LoginlogHasPages> loginlogHasPageses = new HashSet<LoginlogHasPages>(0);

    public Loginlog() {
    }

	
    public Loginlog(User user) {
        this.user = user;
    }
    public Loginlog(User user, Date logintime, Date logouttime, Date logindate, Date logoutdate, String st, Set<Activity> activities, Set<LoginlogHasPages> loginlogHasPageses) {
       this.user = user;
       this.logintime = logintime;
       this.logouttime = logouttime;
       this.logindate = logindate;
       this.logoutdate = logoutdate;
       this.st = st;
       this.activities = activities;
       this.loginlogHasPageses = loginlogHasPageses;
    }
   
    public Integer getIdloginlog() {
        return this.idloginlog;
    }
    
    public void setIdloginlog(Integer idloginlog) {
        this.idloginlog = idloginlog;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getLogintime() {
        return this.logintime;
    }
    
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }
    public Date getLogouttime() {
        return this.logouttime;
    }
    
    public void setLogouttime(Date logouttime) {
        this.logouttime = logouttime;
    }
    public Date getLogindate() {
        return this.logindate;
    }
    
    public void setLogindate(Date logindate) {
        this.logindate = logindate;
    }
    public Date getLogoutdate() {
        return this.logoutdate;
    }
    
    public void setLogoutdate(Date logoutdate) {
        this.logoutdate = logoutdate;
    }
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }
    public Set<Activity> getActivities() {
        return this.activities;
    }
    
    public void setActivities(Set<Activity> activities) {
        this.activities = activities;
    }
    public Set<LoginlogHasPages> getLoginlogHasPageses() {
        return this.loginlogHasPageses;
    }
    
    public void setLoginlogHasPageses(Set<LoginlogHasPages> loginlogHasPageses) {
        this.loginlogHasPageses = loginlogHasPageses;
    }




}


