package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1



/**
 * LoginlogHasPages generated by hbm2java
 */
public class LoginlogHasPages  implements java.io.Serializable {


     private Integer lpid;
     private Loginlog loginlog;
     private Pages pages;

    public LoginlogHasPages() {
    }

    public LoginlogHasPages(Loginlog loginlog, Pages pages) {
       this.loginlog = loginlog;
       this.pages = pages;
    }
   
    public Integer getLpid() {
        return this.lpid;
    }
    
    public void setLpid(Integer lpid) {
        this.lpid = lpid;
    }
    public Loginlog getLoginlog() {
        return this.loginlog;
    }
    
    public void setLoginlog(Loginlog loginlog) {
        this.loginlog = loginlog;
    }
    public Pages getPages() {
        return this.pages;
    }
    
    public void setPages(Pages pages) {
        this.pages = pages;
    }




}


