package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer idproducts;
     private Brand brand;
     private Category category;
     private String pname;
     private Double cprice;
     private Double sprice;
     private String mimg;
     private String des;
     private Integer qty;
     private Integer min;
     private String st;
     private Set<CartHasProducts> cartHasProductses = new HashSet<CartHasProducts>(0);
     private Set<Rating> ratings = new HashSet<Rating>(0);
     private Set<InvoiceHasProducts> invoiceHasProductses = new HashSet<InvoiceHasProducts>(0);
     private Set<Comments> commentses = new HashSet<Comments>(0);

    public Products() {
    }

	
    public Products(Brand brand, Category category) {
        this.brand = brand;
        this.category = category;
    }
    public Products(Brand brand, Category category, String pname, Double cprice, Double sprice, String mimg, String des, Integer qty, Integer min, String st, Set<CartHasProducts> cartHasProductses, Set<Rating> ratings, Set<InvoiceHasProducts> invoiceHasProductses, Set<Comments> commentses) {
       this.brand = brand;
       this.category = category;
       this.pname = pname;
       this.cprice = cprice;
       this.sprice = sprice;
       this.mimg = mimg;
       this.des = des;
       this.qty = qty;
       this.min = min;
       this.st = st;
       this.cartHasProductses = cartHasProductses;
       this.ratings = ratings;
       this.invoiceHasProductses = invoiceHasProductses;
       this.commentses = commentses;
    }
   
    public Integer getIdproducts() {
        return this.idproducts;
    }
    
    public void setIdproducts(Integer idproducts) {
        this.idproducts = idproducts;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public Double getCprice() {
        return this.cprice;
    }
    
    public void setCprice(Double cprice) {
        this.cprice = cprice;
    }
    public Double getSprice() {
        return this.sprice;
    }
    
    public void setSprice(Double sprice) {
        this.sprice = sprice;
    }
    public String getMimg() {
        return this.mimg;
    }
    
    public void setMimg(String mimg) {
        this.mimg = mimg;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Integer getMin() {
        return this.min;
    }
    
    public void setMin(Integer min) {
        this.min = min;
    }
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }
    public Set<CartHasProducts> getCartHasProductses() {
        return this.cartHasProductses;
    }
    
    public void setCartHasProductses(Set<CartHasProducts> cartHasProductses) {
        this.cartHasProductses = cartHasProductses;
    }
    public Set<Rating> getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set<Rating> ratings) {
        this.ratings = ratings;
    }
    public Set<InvoiceHasProducts> getInvoiceHasProductses() {
        return this.invoiceHasProductses;
    }
    
    public void setInvoiceHasProductses(Set<InvoiceHasProducts> invoiceHasProductses) {
        this.invoiceHasProductses = invoiceHasProductses;
    }
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }




}


