package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1



/**
 * RoleHasPages generated by hbm2java
 */
public class RoleHasPages  implements java.io.Serializable {


     private Integer rpid;
     private Pages pages;
     private Role role;
     private String st;

    public RoleHasPages() {
    }

    public RoleHasPages(Pages pages, Role role, String st) {
       this.pages = pages;
       this.role = role;
       this.st = st;
    }
   
    public Integer getRpid() {
        return this.rpid;
    }
    
    public void setRpid(Integer rpid) {
        this.rpid = rpid;
    }
    public Pages getPages() {
        return this.pages;
    }
    
    public void setPages(Pages pages) {
        this.pages = pages;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }




}


