package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer idrole;
     private String rname;
     private String st;
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<RoleHasPages> roleHasPageses = new HashSet<RoleHasPages>(0);

    public Role() {
    }

    public Role(String rname, String st, Set<Login> logins, Set<RoleHasPages> roleHasPageses) {
       this.rname = rname;
       this.st = st;
       this.logins = logins;
       this.roleHasPageses = roleHasPageses;
    }
   
    public Integer getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(Integer idrole) {
        this.idrole = idrole;
    }
    public String getRname() {
        return this.rname;
    }
    
    public void setRname(String rname) {
        this.rname = rname;
    }
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }
    public Set<RoleHasPages> getRoleHasPageses() {
        return this.roleHasPageses;
    }
    
    public void setRoleHasPageses(Set<RoleHasPages> roleHasPageses) {
        this.roleHasPageses = roleHasPageses;
    }




}


