package DB;
// Generated Aug 18, 2018 5:14:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String fname;
     private String lname;
     private String img;
     private String street;
     private String city;
     private String country;
     private Date birthday;
     private String gender;
     private String tel;
     private String mob;
     private String email;
     private Date jdate;
     private String st;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<Loginlog> loginlogs = new HashSet<Loginlog>(0);
     private Set<Urating> uratings = new HashSet<Urating>(0);
     private Set<Chat> chatsForUserIduser = new HashSet<Chat>(0);
     private Set<Chat> chatsForUserIduser1 = new HashSet<Chat>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public User() {
    }

    public User(String fname, String lname, String img, String street, String city, String country, Date birthday, String gender, String tel, String mob, String email, Date jdate, String st, Set<Cart> carts, Set<Login> logins, Set<Loginlog> loginlogs, Set<Urating> uratings, Set<Chat> chatsForUserIduser, Set<Chat> chatsForUserIduser1, Set<Invoice> invoices) {
       this.fname = fname;
       this.lname = lname;
       this.img = img;
       this.street = street;
       this.city = city;
       this.country = country;
       this.birthday = birthday;
       this.gender = gender;
       this.tel = tel;
       this.mob = mob;
       this.email = email;
       this.jdate = jdate;
       this.st = st;
       this.carts = carts;
       this.logins = logins;
       this.loginlogs = loginlogs;
       this.uratings = uratings;
       this.chatsForUserIduser = chatsForUserIduser;
       this.chatsForUserIduser1 = chatsForUserIduser1;
       this.invoices = invoices;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getMob() {
        return this.mob;
    }
    
    public void setMob(String mob) {
        this.mob = mob;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getJdate() {
        return this.jdate;
    }
    
    public void setJdate(Date jdate) {
        this.jdate = jdate;
    }
    public String getSt() {
        return this.st;
    }
    
    public void setSt(String st) {
        this.st = st;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }
    public Set<Loginlog> getLoginlogs() {
        return this.loginlogs;
    }
    
    public void setLoginlogs(Set<Loginlog> loginlogs) {
        this.loginlogs = loginlogs;
    }
    public Set<Urating> getUratings() {
        return this.uratings;
    }
    
    public void setUratings(Set<Urating> uratings) {
        this.uratings = uratings;
    }
    public Set<Chat> getChatsForUserIduser() {
        return this.chatsForUserIduser;
    }
    
    public void setChatsForUserIduser(Set<Chat> chatsForUserIduser) {
        this.chatsForUserIduser = chatsForUserIduser;
    }
    public Set<Chat> getChatsForUserIduser1() {
        return this.chatsForUserIduser1;
    }
    
    public void setChatsForUserIduser1(Set<Chat> chatsForUserIduser1) {
        this.chatsForUserIduser1 = chatsForUserIduser1;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


